import { ErrorCode } from "@/lib/errors/types";

export enum QRErrorCode {
  // QR Code errors (5000-5099)
  QR_CODE_GENERATION_FAILED = "QR_5000",
  QR_CODE_NOT_FOUND = "QR_5001",
  QR_CODE_ALREADY_EXISTS = "QR_5002",
  QR_CODE_INVALID_URL = "QR_5003",

  // Physical Card errors (5100-5199)
  PHYSICAL_CARD_NOT_FOUND = "PHYSICAL_5100",
  PHYSICAL_CARD_ALREADY_LINKED = "PHYSICAL_5101",
  PHYSICAL_CARD_INVALID_SERIAL = "PHYSICAL_5102",
  PHYSICAL_CARD_SCAN_FAILED = "PHYSICAL_5103",
  PHYSICAL_CARD_EMPTY_RECORD = "PHYSICAL_5104",

  // Serial ID errors (5200-5299)
  SERIAL_ID_MISSING = "SERIAL_5200",
  SERIAL_ID_INVALID_FORMAT = "SERIAL_5201",
  SERIAL_ID_ALREADY_USED = "SERIAL_5202",
  SERIAL_ID_NOT_ALLOWED = "SERIAL_5203",

  // Merge errors (5300-5399)
  MERGE_FAILED_CARD_EXISTS = "MERGE_5300",
  MERGE_FAILED_ALREADY_MERGED = "MERGE_5301",
}

export function toErrorCode(code: QRErrorCode): ErrorCode {
  return code as unknown as ErrorCode;
}
